import { designs, designColors } from "./designs";
export const categories = {
  COUPLE: "Couple",
  FAMILY: "Gia đình",
  OCCASION: "Dịp đặc biệt",
} as const;
export const catalog = [
  [
    "couple-1",
    "Phong bì niêm phong tình yêu",
    "COUPLE",
    "#fff8f7",
    "heart",
    "Con dấu sáp đỏ tim vàng, đĩa than xoay & ảnh polaroid kỷ niệm.",
  ],
  [
    "couple-2",
    "Hành trình yêu dấu (Love Counter)",
    "COUPLE",
    "#ffe8eb",
    "heart",
    "Bộ đếm ngày bên nhau nhịp tim, thư tay tình cảm & băng cassette.",
  ],
  [
    "couple-3",
    "Nàng thơ của anh",
    "COUPLE",
    "#fce7e9",
    "flower",
    "Một chút ngọt ngào, dịu dàng dành riêng cho em.",
  ],
  [
    "couple-4",
    "Kỷ niệm ngày chung đôi",
    "COUPLE",
    "#fff0f1",
    "heart",
    "Lưu giữ khoảnh khắc thiêng liêng ngày cưới và ước hẹn trăm năm.",
  ],
  [
    "family-1",
    "Thương mẹ kính yêu",
    "FAMILY",
    "#f8e3d8",
    "flower",
    "Tri ân công ơn sinh thành, gửi mẹ ngàn lời yêu thương ấm áp.",
  ],
  [
    "family-2",
    "Cảm ơn người cha",
    "FAMILY",
    "#dfe9dd",
    "star",
    "Gửi người hùng thầm lặng vững chãi chở che cả gia đình.",
  ],
  [
    "family-3",
    "Tổ ấm bình yên",
    "FAMILY",
    "#fff0ce",
    "heart",
    "Nhà là nơi bão dừng sau cánh cửa, gắn kết mọi thành viên.",
  ],
  [
    "family-4",
    "Gửi người thân xa xứ",
    "FAMILY",
    "#e3ddf2",
    "flower",
    "Dù cách trở vạn dặm, tình cảm gia đình vẫn luôn vẹn nguyên.",
  ],
  [
    "occasion-1",
    "Tết đoàn viên & Rút lì xì",
    "OCCASION",
    "#fdf2e9",
    "flower",
    "Bao lì xì may mắn 3D, bốc quẻ đầu xuân & rộn rã khai xuân đại cát.",
  ],
  [
    "occasion-2",
    "Giáng sinh diệu kỳ & Năm mới",
    "OCCASION",
    "#dcebe5",
    "star",
    "Bông tuyết trắng rơi êm đềm, tiếng chuông ngân và lời chúc bình an.",
  ],
  [
    "occasion-3",
    "Sinh nhật bất ngờ & Khui quà 3D",
    "OCCASION",
    "#fbe6f0",
    "heart",
    "Thổi nến ước nguyện, khui quà 3D tung pháo hoa giấy rực rỡ.",
  ],
  [
    "occasion-4",
    "Tình bạn tri kỷ thanh xuân",
    "OCCASION",
    "#e0e9fa",
    "star",
    "Cuốn sổ lưu bút polaroid dán băng keo washi cùng nhau đi qua thanh xuân.",
  ],
  [
    "couple-5",
    "Lời hẹn dưới ánh trăng",
    "COUPLE",
    "#e8e4f5",
    "star",
    "Lời mời một buổi hẹn, lá thư riêng và món quà bí mật.",
  ],
  [
    "couple-6",
    "Save the date · Ngày của chúng mình",
    "COUPLE",
    "#f5eadb",
    "flower",
    "Thiệp báo hỷ thanh lịch, thời gian, địa điểm và lời mời thân tình.",
  ],
  [
    "family-5",
    "Mừng thọ · Một đời yêu thương",
    "FAMILY",
    "#f5e8d0",
    "flower",
    "Lời chúc sức khỏe ông bà, những kỷ niệm và lời mời sum họp.",
  ],
  [
    "family-6",
    "Hẹn cả nhà về ăn cơm",
    "FAMILY",
    "#e4eddd",
    "heart",
    "Tấm thiệp đoàn tụ với lời nhắn ấm áp và album gia đình.",
  ],
  [
    "occasion-5",
    "Ngày tốt nghiệp rạng rỡ",
    "OCCASION",
    "#e3eafa",
    "star",
    "Lời chúc cho hành trình mới và lời mời cùng lưu lại thanh xuân.",
  ],
  [
    "occasion-6",
    "Tiệc nhỏ · Niềm vui lớn",
    "OCCASION",
    "#f8e3d4",
    "flower",
    "Thiệp mời dự tiệc, thông tin buổi gặp và bất ngờ dành cho khách.",
  ],
].map(([id, name, category, palette, icon, description]) => ({
  id,
  name: designs[id].label,
  category: category as keyof typeof categories,
  palette: designColors[designs[id].id],
  icon,
  description: designs[id].interaction,
}));
