export const designIds = [
  "wax",
  "timeline",
  "poem",
  "cinema",
  "celestial",
  "editorial",
  "botanical",
  "newspaper",
  "scrapbook",
  "postcard",
  "heritage",
  "menu",
  "lunar",
  "winter",
  "birthday",
  "yearbook",
  "graduation",
  "ticket",
] as const;
export type DesignId = (typeof designIds)[number];
export const designs: Record<
  string,
  { id: DesignId; label: string; interaction: string; headline: string }
> = {
  "couple-1": {
    id: "wax",
    label: "Thư niêm sáp",
    interaction: "Chạm mở phong bì",
    headline: "Một lá thư, dành riêng người thương",
  },
  "couple-2": {
    id: "timeline",
    label: "Đường tình yêu",
    interaction: "Cuộn theo từng cột mốc",
    headline: "Từ lần đầu gặp, đến mãi về sau",
  },
  "couple-3": {
    id: "poem",
    label: "Trang thơ",
    interaction: "Chạm lật từng lời nhắn",
    headline: "Em là một mùa dịu dàng",
  },
  "couple-4": {
    id: "cinema",
    label: "Thước phim đôi mình",
    interaction: "Vuốt qua từng khung hình",
    headline: "Chúng mình, trong cùng một thước phim",
  },
  "couple-5": {
    id: "celestial",
    label: "Bản đồ sao",
    interaction: "Chạm sao để mở lời hẹn",
    headline: "Giữa muôn vì sao, mình tìm thấy nhau",
  },
  "couple-6": {
    id: "editorial",
    label: "Tạp chí ngày cưới",
    interaction: "Cuộn đọc chuyện đôi mình",
    headline: "Ngày chúng mình thành một nhà",
  },
  "family-1": {
    id: "botanical",
    label: "Vườn của mẹ",
    interaction: "Chạm nở hoa và đọc thư",
    headline: "Có mẹ, là có một khu vườn bình yên",
  },
  "family-2": {
    id: "newspaper",
    label: "Tờ báo của bố",
    interaction: "Mở từng chuyên mục",
    headline: "Người hùng của những điều bình dị",
  },
  "family-3": {
    id: "scrapbook",
    label: "Album tổ ấm",
    interaction: "Vuốt xem sổ kỷ niệm",
    headline: "Những ngày mình ở bên nhau",
  },
  "family-4": {
    id: "postcard",
    label: "Bưu thiếp xa nhà",
    interaction: "Lật mặt sau bưu thiếp",
    headline: "Xa bao nhiêu, thương bấy nhiêu",
  },
  "family-5": {
    id: "heritage",
    label: "Nếp nhà",
    interaction: "Mở cuộn thư chúc thọ",
    headline: "Phúc như đông hải, thọ tựa nam sơn",
  },
  "family-6": {
    id: "menu",
    label: "Bữa cơm nhà",
    interaction: "Mở từng món chuyện nhà",
    headline: "Hôm nay, nhà mình ăn gì?",
  },
  "occasion-1": {
    id: "lunar",
    label: "Xuân đỏ",
    interaction: "Chạm mở lộc xuân",
    headline: "Một năm mới, vạn điều lành",
  },
  "occasion-2": {
    id: "winter",
    label: "Quả cầu tuyết",
    interaction: "Chạm cho tuyết rơi",
    headline: "Một mùa an lành, một đời ấm áp",
  },
  "occasion-3": {
    id: "birthday",
    label: "Sân khấu sinh nhật",
    interaction: "Chạm tắt nến, mở điều ước",
    headline: "Hôm nay, bạn là nhân vật chính!",
  },
  "occasion-4": {
    id: "yearbook",
    label: "Lưu bút thanh xuân",
    interaction: "Lật trang sổ lưu bút",
    headline: "Chúng ta của những năm tháng ấy",
  },
  "occasion-5": {
    id: "graduation",
    label: "Chương mới",
    interaction: "Mở cuộn lời chúc tốt nghiệp",
    headline: "The next chapter starts with you",
  },
  "occasion-6": {
    id: "ticket",
    label: "Vé đến niềm vui",
    interaction: "Xé vé để mở lời mời",
    headline: "Một tối thật vui, có bạn và chúng mình",
  },
};

export const designColors: Record<DesignId, string> = {
  wax: "#fff8f7",
  timeline: "#f0ebe2",
  poem: "#ece9f0",
  cinema: "#151618",
  celestial: "#111e35",
  editorial: "#f5f1e9",
  botanical: "#e8eddf",
  newspaper: "#e9e4d8",
  scrapbook: "#f0dabb",
  postcard: "#faf0d9",
  heritage: "#ede0bc",
  menu: "#fff8df",
  lunar: "#a32d27",
  winter: "#e0edf0",
  birthday: "#f8f047",
  yearbook: "#f3edda",
  graduation: "#173b30",
  ticket: "#5039bd",
};
